[build]
  publish = "public"  # Directory containing your static files

[functions]
  directory = "functions"  # Directory containing your Netlify functions

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/form"
  to = "/.netlify/functions/form"
  status = 200